### ISSUE TITLE
Invalid enum value on HATCHET_CLIENT_TLS_STRATEGY

### ISSUE THREAD

**Issue by sk1ter** [hatchet-dev/hatchet-typescript#14]
Hi! Locally running hatchet server, when `HATCHET_CLIENT_TLS_STRATEGY=none` gives error:
```
Error: Invalid client config: [
  {
    "received": "none",
    "code": "invalid_enum_value",
    "options": [
      "tls",
      "mtls"
    ],
    "path": [
      "tls_config",
      "tls_strategy"
    ],
    "message": "Invalid enum value. Expected 'tls' | 'mtls', received 'none'"
  }
]
```

**Comment by grutt** [comment]
Hi @sk1ter 
I'll push a fix for this.

Also, one thing to note currently TLS is handled by Caddy, you should be able to specify a ROOT CA File similar to my path:

HATCHET_CLIENT_TLS_ROOT_CA_FILE="/Users/gabrielruttner/Library/Application Support/Caddy/pki/authorities/local/root.crt"

Will also revise docs to reflect this.
